# source: https://github.com/grafana/prometheus-alertmanager-tutorial/blob/main/docker-compose.yaml
# source: https://github.com/grafana/prometheus-alertmanager-tutorial/blob/main/alertmanager/alertmanager.yml
# source: https://hub.docker.com/r/prom/alertmanager
#
# networks assumes there is an existing docker network "monitoring"

services:
  alertmanager:
    image: prom/alertmanager:v0.34.0
    container_name: alertmanager
    restart: unless-stopped

    networks:
      - monitoring

    ports:
      - "9093:9093"

    volumes:
      - ./alertmanager.yaml:/etc/alertmanager/alertmanager.yaml:ro

    command:
      - "--config.file=/etc/alertmanager/alertmanager.yaml"

networks:
  monitoring:
    external: true
