# source: https://github.com/grafana/prometheus-alertmanager-tutorial/blob/main/docker-compose.yaml
# source: https://github.com/grafana/prometheus-alertmanager-tutorial/blob/main/alertmanager/alertmanager.yml

