# source: https://github.com/louislam/uptime-kuma/blob/master/compose.yaml
#
# Changed from a Docker named volume to a local bind mount
# to simplify backups and migration between Docker hosts.

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped

    networks:
      - monitoring

    ports:
      - "3001:3001"

    volumes:
      - ./data:/app/data

networks:
  monitoring:
    external: true
