# source: https://prometheus.io/docs/prometheus/latest/installation/#using-docker

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # Relative to this Compose file: /opt/docker/prometheus/prometheus.yml
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

volumes:
  prometheus-data:
