# source: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# example: https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml
#
# targets: endpoints Prometheus scrapes; can use container names, IP addresses,
# or DNS names as long as they are reachable from Prometheus

global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yaml"

scrape_configs:
  # Linux host metrics collected by Node Exporter
  - job_name: node-exporter
    static_configs:
      - targets:
          - 10.10.10.108:9100

  # Docker container metrics collected by cAdvisor
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  # HTTP/HTTPS availability checks collected by Blackbox Exporter
  - job_name: blackbox-http
    metrics_path: /probe

    params:
      module:
        - http_2xx

    static_configs:
      - targets:
          - https://google.com
          - http://10.10.10.108:3000

    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target

      - source_labels:
          - __param_target
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Network device metrics collected through SNMP Exporter
  - job_name: snmp
    metrics_path: /snmp

    params:
      auth:
        - public_v2
      module:
        - if_mib

    static_configs:
      - targets:
          - 10.10.10.2

    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target

      - source_labels:
          - __param_target
        target_label: instance

      - target_label: __address__
        replacement: snmp-exporter:9116
