global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/*.yaml"

scrape_configs:
  # your scrape targets here
