# source: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# example: https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml

# targets: endpoints Prometheus scrapes; can use container names, IP addresses,
# or DNS names as long as they are reachable from Prometheus

global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yaml"

scrape_configs:
  # your scrape targets here
